path:
  train_path: './newdata/my_train.json'
  test_path: './newdata/my_test.json'
  # 意图lable
  seq_labels_path: './newdata/intents.txt'
  # 实体lable
  token_labels_path: './newdata/slots.txt'
  # 预训练模型dir
  bert_dir: './chinese-bert-wwm-ext/'
  save_dir: './newdata/checkpoints/'
  load_dir: './newdata/checkpoints/model.pt'

